name: Kubenetes cd
on:
 
  push:
 
    branches: [ main ]
env:
 
  ECR_REPOSITORY: eks-ecr
 
  EKS_CLUSTER_NAME: ekscluster
 
  AWS_REGION: us-east-2
jobs:
 
  build:
 
    name: Deployment
 
    runs-on: ubuntu-latest
    steps:
    - name: Update kube config
 
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
    - name: Deploy to EKS
 
      env:
 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}        
 
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
 
      run: |
 
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml

        
